# Deploy a full containerized GNOME Desktop through Apache Guacamole
---
- name: Guacamole Setup
  hosts: guacamole

  vars:
  - guacamole_path: /usr/local/containerized-guacamole

  - required_packages:
      - git
      - xrdp
      - fail2ban
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python2-pip

  tasks:
  - name: Load secrets
    include_vars:
      file: secrets

  - name: Debug
    debug:
      var:
      - ansible_fqdn

  - name: Deploy Docker CE Repository
    yum_repository:
      name: docker-ce
      description: Docker CE Repo
      baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
      enabled: true
    #notify:
    #- Add Docker CE GPG Key

  - name: Add Docker CE GPG Key
    rpm_key:
      state: present
      key: https://download.docker.com/linux/centos/gpg

  - name: Deploy EPEL Repository
    package:
      name: epel-release
      state: present

  - name: Deploy required packages
    package:
      name: "{{ required_packages }}"
      state: present
    notify:
    - Enable XRDP
    - Enable Docker
    #loop: "{{ required_packages }}"

  - name: Deploy Docker Compose
    get_url: 
      url : https://github.com/docker/compose/releases/download/1.28.6/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 'u+x,g+x'

  - name: Deploy GNOME Desktop
    package:
      #name: "@GNOME Desktop"
      name: "@^gnome-desktop-environment"
      state: present

  - name: Remove libvirt / GNOME Boxes
    package:
      name: libvirt-daemon-driver-network
      state: absent
    notify: Disable libvirtd

  - name: Deploy Containerized Guacamole
    git:
      repo: 'https://github.com/alienmind/containerized-guacamole.git'
      dest: '{{ guacamole_path }}'

  - name: Deploy Guacamole Config
    template:
      src: guacamole/env.j2
      dest: '{{ guacamole_path }}/.env'
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  - name: Deploy Guacamole Redirection Page
    template:
      src: guacamole/index.jsp
      dest: '{{ guacamole_path }}/index.jsp'
      owner: root
      group: root
      mode: u=rw,g=r,o=r

  - name: Deploy Guacamole Helper Script
    template:
      src: guacamole/start.sh
      dest: '{{ guacamole_path }}/start.sh'
      owner: root
      group: root
      mode: u=rwx,g=rx,o=rx


  #- name: Deploy Docker Python API
  #pip:
  #  name:
  #  - docker>=1.8.0
  #  - PyYAML>=3.11
  #  #- docker-compose>=1.7.0

  #- name: Start Guacamole Containers
  # community.docker.docker_compose:
  #   project_src: '{{ guacamole_path }}'
  #   state: present

  - name: Start Guacamole Containers
    command:
      chdir: '{{ guacamole_path }}'
      cmd: '{{ guacamole_path }}/start.sh'

  handlers:
  - name: Add Docker CE GPG Key
    rpm_key:
      state: present
      key: https://download.docker.com/linux/centos/gpg
  - name: Enable XRDP
    service:
      name: xrdp
      enabled: yes
      state: restarted
  - name: Enable Docker
    service:
      name: docker
      enabled: yes
      state: restarted
  - name: Disable libvirtd
    service:
      name: libvirtd
      enabled: no
      state: stopped
  - name: Kill all dnsmasq
    command:
      cmd: killall dnsmasq
 
